_target_: neural_local_laplacian.data_modules.common.GenericDataModule
train_dataset_specification:
  _target_: neural_local_laplacian.data_modules.common.DatasetSpecification
  dataset:
    _target_: neural_local_laplacian.datasets.synthetic_datasets.PolynomialSurfaceDataset
    seed: ${globals.seed}
    epoch_size: 1000
    grid_radius_range: [2.0]
    grid_offset_range: [0.0]
    points_scale_range: [1.0]
    coefficient_scale_range: [0.01]
    order_range: [2, 4]
    grid_samplers:
      - _target_: neural_local_laplacian.datasets.synthetic_datasets.RegularGridSampler
        num_points: 1000
      - _target_: neural_local_laplacian.datasets.synthetic_datasets.RandomGridSampler
        num_points_range: 10
    feature_extractor:
        _target_: neural_local_laplacian.utils.features.XYZFeatureExtractor
        num_fourier_features: 512
        use_fourier: False
    diff_geom_at_origin_only: True
    conv_k_nearest: null
    pose_transformer:
        _target_: neural_local_laplacian.utils.pose_transformers.AlignNormalZTransformer
    coeff_generation_method:
      _target_: neural_local_laplacian.datasets.synthetic_datasets.CoeffGenerationMethod
      _args_: ['uniform']
    diff_geom_components:
      - _target_: neural_local_laplacian.datasets.synthetic_datasets.DifferentialGeometryComponent
        _args_: ['mean_curvature']
      - _target_: neural_local_laplacian.datasets.synthetic_datasets.DifferentialGeometryComponent
        _args_: ['gaussian_curvature']
      - _target_: neural_local_laplacian.datasets.synthetic_datasets.DifferentialGeometryComponent
        _args_: ['principal_curvatures']
      - _target_: neural_local_laplacian.datasets.synthetic_datasets.DifferentialGeometryComponent
        _args_: ['principal_directions']
      - _target_: neural_local_laplacian.datasets.synthetic_datasets.DifferentialGeometryComponent
        _args_: ['mean_curvature']
    flip_normal_if_negative_curvature: False
  batch_size: 1
  num_workers: 0
  shuffle: True
val_dataset_specifications: null