_target_: lightning.pytorch.Trainer
max_epochs: -1
devices: -1
accelerator: 'auto'
strategy: 'auto'
num_sanity_val_steps: 0
log_every_n_steps: 1
check_val_every_n_epoch: 500
enable_progress_bar: True
logger:
 _target_: lightning.pytorch.loggers.WandbLogger
 project: neural-local-laplacian
 save_dir: 'wandb'
 log_model: 'all'
 checkpoint_name: 'model'
#callbacks:
#  - _target_: neural_local_laplacian.modules.laplacian_modules.ValidationMeshUploader
callbacks:
  - _target_: neural_local_laplacian.modules.laplacian_modules.DebugCallback
  - _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: "./checkpoints"
    filename: "model-{epoch:010d}-{train_loss:.4f}"
    monitor: "train_loss"
    mode: "min"
    save_top_k: 1
    save_last: true
    verbose: true
    save_on_train_epoch_end: true
