_target_: lightning.pytorch.Trainer
max_epochs: -1
devices: -1
accelerator: 'auto'
strategy: 'auto'
num_sanity_val_steps: 0
log_every_n_steps: 1
check_val_every_n_epoch: 20
enable_progress_bar: True
#logger: False
logger:
 _target_: lightning.pytorch.loggers.WandbLogger
 project: neural-cotangent-weights
 save_dir: 'wandb'
 log_model: 'all'
callbacks:
  - _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: "./checkpoints"
    filename: "model-{epoch:010d}"
    monitor: "val/geodesic_correlation_mean"
    mode: "max"
    save_top_k: 1
    save_last: False
    verbose: False
    save_on_train_epoch_end: True