_target_: neural_local_laplacian.data_modules.common.GenericDataModule
train_dataset_specification: null
val_dataset_specifications:
  - _target_: neural_local_laplacian.data_modules.common.DatasetSpecification
    dataset:
      _target_: neural_local_laplacian.datasets.mesh_datasets.MeshDataset
      mesh_folder_path: './assets/meshes4'
      k: 20
      feature_extractor:
        _target_: neural_local_laplacian.utils.features.XYZFeatureExtractor
      pose_transformers:
        - _target_: neural_local_laplacian.utils.pose_transformers.RandomRotationTransformer
    batch_size: 1
    num_workers: 0
    shuffle: False