_target_: neural_local_laplacian.data_modules.common.GenericDataModule
train_dataset_specification: null
val_dataset_specifications:
  - _target_: neural_local_laplacian.data_modules.common.DatasetSpecification
    dataset:
      _target_: neural_local_laplacian.datasets.mesh_datasets.MeshDataset
      mesh_folder_path: './assets/meshes2'
      k: 10
      feature_extractor:
        _target_: neural_local_laplacian.utils.features.XYZFeatureExtractor
      pose_transformers: null
    batch_size: 1
    num_workers: 0
    shuffle: False