_target_: neural_local_laplacian.data_modules.common.GenericPygDataModule
train_dataset_specification: null
val_dataset_specifications:
  - _target_: neural_local_laplacian.data_modules.common.DatasetSpecification
    dataset:
      _target_: neural_local_laplacian.datasets.mesh_datasets.MeshDataset
      mesh_folder_path: 'F:\input\Thingi10k'
      max_meshes: 100
      file_size_range_mb: [0.2, 2]
      num_components_range: [1, 1]
      shuffle: True
      k: 30
      pose_transformers:
        - _target_: neural_local_laplacian.utils.pose_transformers.RandomRotationTransformer
    batch_size: 1
    num_workers: 0
    shuffle: False