module:
  _target_: neural_local_laplacian.modules.laplacian_modules.LaplacianTransformerModule
  input_dim: 3
  d_model: 128
  nhead: 4
  num_encoder_layers: 6
  dim_feedforward: 128
  num_eigenvalues: ${globals.num_eigenvalues}
#  use_permutation_invariant: True
  dropout: 0.0
  normalize_loss_weights: False
  normalize_patch_features: True
  scale_areas_by_patch_size: True
  input_projection_hidden_dims: [32, 64]
  output_projection_hidden_dims: [64, 32]
  loss_configs:
#    - _target_: neural_local_laplacian.modules.losses.LossConfig
#      loss_module:
#        _target_: neural_local_laplacian.modules.losses.VectorMSELoss
#      weight: 1
    - _target_: neural_local_laplacian.modules.losses.LossConfig
      loss_module:
        _target_: neural_local_laplacian.modules.losses.DirectionCosineLoss
      weight: 100
    - _target_: neural_local_laplacian.modules.losses.LossConfig
      loss_module:
        _target_: neural_local_laplacian.modules.losses.MagnitudeMSELoss
      weight: 1