module:
  _target_: neural_local_laplacian.modules.laplacian_modules.LaplacianTransformerModule
  input_dim: 3
  d_model: 256
  nhead: 16
  num_encoder_layers: 6
  dim_feedforward: 256
  num_eigenvalues: ${globals.num_eigenvalues}
#  use_permutation_invariant: True
  dropout: 0.0
  normalize_loss_weights: False
  input_projection_hidden_dims: [32, 64, 128]
  output_projection_hidden_dims: [128, 64, 32]
  loss_configs:
    - loss_module:
        _target_: neural_local_laplacian.modules.losses.NormalDirectionCosineLoss
      weight: 1.0
#    - loss_module:
#        _target_: neural_local_laplacian.modules.losses.NormalMagnitudeLoss
#      weight: 1.0
#    - loss_module:
#        _target_: neural_local_laplacian.modules.losses.MeanCurvatureMSELoss
#      weight: 1.0