module:
  _target_: neural_local_laplacian.modules.laplacian_modules.LaplacianTransformerModule
  input_dim: 3
  d_model: 512
  nhead: 8
  num_encoder_layers: 1
  dim_feedforward: 512
  num_eigenvalues: ${globals.num_eigenvalues}
  dropout: 0.2
  normalize_loss_weights: False
  normalize_patch_features: True
  scale_areas_by_patch_size: True
  input_projection_hidden_dims: null
  output_projection_hidden_dims: null

  detach_area_head: false
  use_uniform_mass: false

  area_activation: bounded_sigmoid
  area_bound_C: 5.0

  mcv_mode: 'diagonal_gram'
  normalize_grad_by_k: true

  val_laplacian:
    assembly: diagonal_gram
    pruning: none

  fmap_val_cfg:
    k: 15
    num_eigenvectors: 100
    max_vertices_val: 5000
    eval_laplacians:
      - assembly: diagonal_gram
        pruning: none
        area_weighted: false
    geo_cache_dir: ./geo_cache
    use_geomfum_eval: true
    geomfum_descriptors: [hks, wks]
    geomfum_zoomout: false
    geomfum_zoomout_k_init: 20
    geomfum_zoomout_k_final: 50
    geomfum_zoomout_n_iters: 10

  feature_extractor: null
  loss_configs:
    - _target_: neural_local_laplacian.modules.losses.LossConfig
      loss_module:
        _target_: neural_local_laplacian.modules.losses.DirectionCosineLoss
      weight: 2.0
    - _target_: neural_local_laplacian.modules.losses.LossConfig
      loss_module:
        _target_: neural_local_laplacian.modules.losses.AreaOnlyLogMagnitudeLoss
      weight: 0.001

#    - _target_: neural_local_laplacian.modules.losses.LossConfig
#      loss_module:
#        _target_: neural_local_laplacian.modules.losses.DirectionCosineLoss
#      weight: 1.0
#    - _target_: neural_local_laplacian.modules.losses.LossConfig
#      loss_module:
#        _target_: neural_local_laplacian.modules.losses.AreaOnlyLogMagnitudeLoss
#      weight: 2.0

#    - _target_: neural_local_laplacian.modules.losses.LossConfig
#      loss_module:
#        _target_: neural_local_laplacian.modules.losses.DirectionCosineLoss
#      weight: 1.0
#    - _target_: neural_local_laplacian.modules.losses.LossConfig
#      loss_module:
#        _target_: neural_local_laplacian.modules.losses.StiffnessActionLoss
#      weight: 1.0
    - _target_: neural_local_laplacian.modules.losses.LossConfig
      loss_module:
        _target_: neural_local_laplacian.modules.losses.AreaSupervisionLoss
      weight: 30.0