module:
  _target_: neural_local_laplacian.modules.laplacian_modules.LaplacianTransformerModule
  input_dim: 3
  d_model: 512
  nhead: 32
  num_encoder_layers: 6
  dim_feedforward: 512
  num_eigenvalues: ${globals.num_eigenvalues}
  dropout: 0.1
  normalize_loss_weights: True
  normalize_patch_features: True
  scale_areas_by_patch_size: True
  input_projection_hidden_dims: [16, 32]
  output_projection_hidden_dims: [32, 16]
  loss_configs:
    - _target_: neural_local_laplacian.modules.losses.LossConfig
      loss_module:
        _target_: neural_local_laplacian.modules.losses.DirectionCosineLoss
      weight: 16000.0
    - _target_: neural_local_laplacian.modules.losses.LossConfig
      loss_module:
        _target_: neural_local_laplacian.modules.losses.LogMagnitudeLoss
      weight: 1.0
    - _target_: neural_local_laplacian.modules.losses.LossConfig
      loss_module:
        _target_: neural_local_laplacian.modules.losses.TangentPlaneProjectorLoss
      weight: 1.0
    - _target_: neural_local_laplacian.modules.losses.LossConfig
      loss_module:
        _target_: neural_local_laplacian.modules.losses.DirichletEnergyConsistencyLoss
        num_random_probes: 100
        probe_mode: 'coordinates'
      weight: 1.0
