# fmaps_config/data_module/humanoids_inter.yaml

module:
  _target_: neural_local_laplacian.data_modules.common.GenericPlainDataModule
  train_dataset_specification:
    _target_: neural_local_laplacian.data_modules.common.DatasetSpecification
    dataset:
      _target_: fmaps_finetune.datasets.functional_map_dataset.ShapePairDataset
      pair_generator:
        _target_: fmaps_finetune.datasets.functional_map_dataset.DT4DAnimalsPairGenerator
        root: '/workspace/datasets/DeformingThings4DMatching-Animals'
        pairs: [0.7]
      num_samples: 160
      seed: ${globals.training_seed}
    batch_size: 2
    num_workers: 0
    shuffle: true
    collate_fn:
      _target_: fmaps_finetune.datasets.functional_map_dataset.pair_collate_fn
      _partial_: true
  val_dataset_specifications:
    - _target_: neural_local_laplacian.data_modules.common.DatasetSpecification
      dataset:
        _target_: fmaps_finetune.datasets.functional_map_dataset.ValPairDataset
        pair_generator:
          _target_: fmaps_finetune.datasets.functional_map_dataset.DT4DAnimalsPairGenerator
          root: '/workspace/datasets/DeformingThings4DMatching-Animals'
          pairs: ["0.7:1.0"]
        val_poses_per_pair: 15
        seed: ${globals.training_seed}
      batch_size: 1
      num_workers: 0
      shuffle: false
      collate_fn:
        _target_: fmaps_finetune.datasets.functional_map_dataset.pair_collate_fn
        _partial_: true