# fmaps_config/data_module/dt4d.yaml
# DeformingThings4DMatching Humanoids — pre-loaded mesh sequences.
#
# Required CLI overrides:
#   data_module.module.train_dataset_specification.dataset.pair_generator.root=<path>
#   data_module.module.val_dataset_specifications.0.dataset.pair_generator.root=<path>

module:
  _target_: neural_local_laplacian.data_modules.common.GenericPlainDataModule

  train_dataset_specification:
    _target_: neural_local_laplacian.data_modules.common.DatasetSpecification
    dataset:
      _target_:  fmaps_finetune.datasets.functional_map_dataset.ShapePairDataset
      pair_generator:
        _target_: fmaps_finetune.datasets.functional_map_dataset.DT4DPairGenerator
        root: 'F:\3DV22_DeformingThings4DMatching_dataset-main\DeformingThings4DMatching'                  # path to DeformingThings4DMatching root
        train_categories: null     # null → auto: all categories except last 2
        val_categories: null       # null → auto: last 2 categories alphabetically
      num_samples: 200
      cross_ratio: 0.0
    batch_size: 5
    num_workers: 0
    shuffle: true
    collate_fn:
      _target_: fmaps_finetune.datasets.functional_map_dataset.pair_collate_fn
      _partial_: true

  val_dataset_specifications:
    - _target_: neural_local_laplacian.data_modules.common.DatasetSpecification
      dataset:
        _target_: fmaps_finetune.datasets.functional_map_dataset.ValPairDataset
        pair_generator:
          _target_: fmaps_finetune.datasets.functional_map_dataset.DT4DPairGenerator
          root: 'F:\3DV22_DeformingThings4DMatching_dataset-main\DeformingThings4DMatching'
          train_categories: null
          val_categories: null
        val_poses_per_pair: 2
        seed: ${globals.training_seed}
      batch_size: 1
      num_workers: 0
      shuffle: false
      collate_fn:
        _target_: fmaps_finetune.datasets.functional_map_dataset.pair_collate_fn
        _partial_: true